DOCUMENT=cv_11.tex
.PHONY: all clean
all:
	pdflatex -interaction=nonstopmode $(DOCUMENT)
	pdflatex -interaction=nonstopmode $(DOCUMENT)
clean:
	rm -f *.pdf
	rm -f *.log
	rm -f *.lol
	rm -f *.lof
	rm -f *.toc
	rm -f *.out
	rm -f *.aux

